### PR TITLE
Clean and fix CSS

### PR DESCRIPTION
**Pull request by moeenio**
- Consistent spacing/indentation
- Put `@import` inside of a CSS rule
- Remove the `&`, since it needs a [preprocessor](https://htmlmag.com/article/an-introduction-to-css-preprocessors-sass-less-stylus).

### CODE REVIEW

**Comment by githubfan** [comment]
Merged.

**Comment by githubfan** [comment]
Can you check out the new commits on the html files?

**Comment by moeenio** [comment]
Please clean your spacing. I like to help but it's up to you to give a proper something that I can help with.

**Comment by githubfan** [comment]
I'll try

**Comment by githubfan** [comment]
Hey, are you on slack?

**Comment by moeenio** [comment]
Not really, why ?

**Comment by githubfan** [comment]
I created a Coding Master one

**Comment by moeenio** [comment]
ok

**Pull request merged**
